### ISSUE TITLE
Dynamic Data

### ISSUE THREAD

**Issue by bluznierca1** [zorfling/react-symfony-4-starter#2]
When data is hard coded - it can be easily retrieved by React thanks to fetch().
The problem occurs when the data, in this case of User, is converted into Json file which bases on logged-in user or session - then 500 Internal Server Error comes and because of that - Json is not generated correctly.
What i mean exactly is: when I want to retrieve user object from DB by finding it by specified ID, it works but when i want to retrieve that ID from existing session or logged-in user - it does not work.
Any idea how to fix it ?

**Comment by zorfling** [comment]
Sorry I missed this - I'm assuming it's no longer necessary.
